

import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Bot, Zap, Shield, BarChart3, Users2, 
  ArrowRight, Sparkles, BrainCircuit, 
  Search, FileText, Target, Award, ChevronDown, Laptop, Building2, Rocket, Check
} from 'lucide-react';

const LandingPage = () => {
  const [activeTab, setActiveTab] = useState('candidate');
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const fadeInUp = {
    initial: { opacity: 0, y: 30 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.6 }
  };

  const candidateFeatures = [
    { icon: <FileText />, title: "AI Resume Scoring", desc: "Know your worth before you apply. AI scores your resume against 10,000+ job benchmarks." },
    { icon: <Target />, title: "Personalized Roadmap", desc: "Bridge the gap. Get a custom learning path generated by AI to land your dream job." },
    { icon: <Award />, title: "Smart Interview Prep", desc: "Real-time mock interviews with AI that asks questions based on your specific profile." }
  ];

  const hrFeatures = [
    { icon: <BarChart3 />, title: "Neural Candidate Ranking", desc: "Stop manual screening. AI finds the top 1% match from thousands of applications in seconds." },
    { icon: <Search />, title: "Deep Skill Analysis", desc: "Understand candidate potential beyond keywords with our semantic skill mapping." },
    { icon: <Bot />, title: "Automated Talent Pipeline", desc: "Let AI tag, categorize, and manage your talent pool while you focus on interviews." }
  ];

  return (
    <div className="min-h-screen bg-[#fafafa] text-[#1a1a1a] font-sans selection:bg-blue-600 selection:text-white overflow-x-hidden scroll-smooth">
      
      {/* --- PREMIUM NAVBAR --- */}
      <nav className={`fixed top-0 w-full z-[100] transition-all duration-500 ${
        isScrolled 
        ? "bg-slate-950/95 backdrop-blur-xl py-4 border-b border-white/10 shadow-2xl" 
        : "bg-transparent py-7"
      }`}>
        <div className="max-w-[1400px] mx-auto px-8 flex items-center justify-between">
          
          <div className="flex items-center gap-2.5 group cursor-pointer" onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}>
            <div className={`p-2 rounded-xl transition-all ${isScrolled ? 'bg-blue-600 shadow-blue-500/30' : 'bg-slate-950/5 border'}`}>
              <BrainCircuit className={`${isScrolled ? 'text-white' : 'text-slate-950'}`} size={26} />
            </div>
            <span className={`text-2xl font-[1000] tracking-tighter transition-colors ${isScrolled ? 'text-white' : 'text-slate-950'}`}>
              SmartHire<span className="text-blue-500">.</span>
            </span>
          </div>
          
          <div className={`hidden md:flex items-center gap-10 text-[12px] font-black uppercase tracking-[0.15em] transition-colors ${isScrolled ? 'text-slate-300' : 'text-slate-500'}`}>
            <a href="#features" className="hover:text-blue-500 transition-colors">Features</a>
            {/* ID se link kiya hai */}
            <a href="#pricing" className="hover:text-blue-500 transition-colors">Pricing</a>
            <a href="#about" className="hover:text-blue-500 transition-colors">About</a>
          </div>

          <div className="flex items-center gap-8">
            <Link to="/login-candidate" className={`text-xs font-black uppercase tracking-widest hover:text-blue-500 transition-colors ${isScrolled ? 'text-white' : 'text-slate-700'}`}>
              Sign In
            </Link>
            <Link to="/register-candidate" className="relative overflow-hidden bg-slate-900 text-white px-8 py-3.5 rounded-full text-[12px] font-black uppercase tracking-widest group shadow-2xl shadow-slate-950/20 active:scale-95 transition-all">
              <span className="relative z-10 flex items-center gap-2">Get Started <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform"/></span>
              <div className="absolute inset-0 bg-gradient-to-r from-blue-600 to-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
            </Link>
          </div>
        </div>
      </nav>

      {/* --- HERO SECTION --- */}
      <section className="pt-64 pb-32 px-6 relative">
        <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/4 w-[800px] h-[800px] bg-blue-50 rounded-full blur-[120px] -z-10" />
        <div className="max-w-[1200px] mx-auto relative z-10">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col items-center text-center">
            <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-100 text-blue-700 px-4 py-1.5 rounded-full text-[12px] font-black uppercase tracking-[0.15em] mb-12 shadow-inner shadow-blue-100">
              <Sparkles size={14} className="animate-pulse"/> Intelligence that recruits for you
            </div>
            <h1 className="text-7xl md:text-[110px] font-[1000] leading-[1.0] tracking-[-0.04em] text-slate-950 mb-10 pb-2">
              Hiring evolved <br /> 
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-500">with AI.</span>
            </h1>
            <p className="text-xl text-slate-500 max-w-2xl font-medium leading-relaxed mb-14 mx-auto">
              SmartHire uses advanced neural networks to bridge the gap between world-class talent and top-tier opportunities.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
              <Link to="/login-candidate" className="group bg-blue-600 text-white px-10 py-6 rounded-[28px] font-black text-xl shadow-2xl shadow-blue-200 hover:bg-blue-700 transition-all flex items-center gap-3 active:scale-95">
                Join as Candidate <ArrowRight className="group-hover:translate-x-2 transition-transform" />
              </Link>
              <Link to="/login-hr" className="bg-white border-2 border-slate-200 text-slate-950 px-10 py-6 rounded-[28px] font-black text-xl hover:border-blue-600 hover:text-blue-600 hover:shadow-xl hover:shadow-blue-50 transition-all active:scale-95">
                Recruiter Portal
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* --- ABOUT SECTION --- */}
      <section id="about" className="py-32 bg-white px-6">
        <div className="max-w-[1200px] mx-auto">
          <div className="grid lg:grid-cols-2 gap-24 items-center mb-40">
            <motion.div {...fadeInUp}>
              <h4 className="text-blue-600 font-black tracking-[0.2em] uppercase text-sm mb-6">Our DNA</h4>
              <h2 className="text-5xl md:text-7xl font-[1000] text-slate-900 leading-[0.95] tracking-tighter mb-8">
                The Engine of <br /> Modern Work.
              </h2>
              <p className="text-lg text-slate-500 font-medium leading-relaxed max-w-xl">
                We are a neural ecosystem designed to solve the world's most complex hiring challenges using ethical AI and deep data science.
              </p>
            </motion.div>
            <div className="grid grid-cols-2 gap-5">
              {[
                { label: "Matches Made", val: "2M+" },
                { label: "Time Saved", val: "85%" },
                { label: "Accuracy", val: "99%" },
                { label: "Enterprise Partners", val: "500+" }
              ].map((s, i) => (
                <div key={i} className="p-9 bg-slate-50 rounded-[40px] border border-slate-100 hover:border-blue-100 hover:shadow-xl transition-all">
                  <div className="text-4xl font-[1000] text-blue-600 mb-1.5 tracking-tighter">{s.val}</div>
                  <div className="text-slate-400 font-bold text-xs uppercase tracking-widest">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* --- FEATURES SECTION --- */}
      <section id="features" className="py-32 bg-slate-100/70 px-6 rounded-[70px] mx-4 md:mx-10 mb-24 border border-slate-200/50">
        <div className="max-w-[1200px] mx-auto text-center">
          <h2 className="text-5xl md:text-6xl font-[1000] tracking-tight mb-16 text-slate-900 leading-tight">
            Built for both <span className="text-blue-600">sides.</span>
          </h2>
          <div className="inline-flex p-2 bg-white rounded-[32px] mb-20 shadow-2xl shadow-slate-200/40 border border-slate-100">
            <button onClick={() => setActiveTab('candidate')} className={`flex items-center gap-2.5 px-9 py-4.5 rounded-[26px] text-lg font-black transition-all duration-300 ${activeTab === 'candidate' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-slate-600'}`}>
              <Users2 size={20} /> Candidate
            </button>
            <button onClick={() => setActiveTab('hr')} className={`flex items-center gap-2.5 px-9 py-4.5 rounded-[26px] text-lg font-black transition-all duration-300 ${activeTab === 'hr' ? 'bg-slate-900 text-white shadow-lg' : 'text-slate-400 hover:text-slate-600'}`}>
              <Zap size={20} /> Recruiter
            </button>
          </div>
          <div className="min-h-[450px]">
            <AnimatePresence mode="wait">
              <motion.div key={activeTab} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} transition={{duration: 0.4}} className="grid md:grid-cols-3 gap-8">
                {(activeTab === 'candidate' ? candidateFeatures : hrFeatures).map((feat, i) => (
                  <div key={i} className={`p-11 rounded-[50px] border text-left transition-all duration-500 group hover:-translate-y-5 shadow-sm ${activeTab === 'candidate' ? 'bg-white border-slate-100 hover:shadow-2xl shadow-blue-100' : 'bg-slate-950 border-slate-800 text-white hover:shadow-2xl shadow-black/20'}`}>
                    <div className={`w-15 h-15 rounded-3xl flex items-center justify-center mb-9 shadow-lg ${activeTab === 'candidate' ? 'bg-blue-600 text-white' : 'bg-white text-slate-900'}`}>
                      {React.cloneElement(feat.icon, {size: 26})}
                    </div>
                    <h3 className="text-2xl font-[1000] mb-5 tracking-tight">{feat.title}</h3>
                    <p className={`${activeTab === 'candidate' ? 'text-slate-500' : 'text-slate-400'} font-medium leading-relaxed`}>{feat.desc}</p>
                  </div>
                ))}
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      </section>

      {/* --- PRICING SECTION (Added here) --- */}
      <section id="pricing" className="py-32 bg-white px-6">
        <div className="max-w-[1200px] mx-auto text-center">
          <motion.div {...fadeInUp}>
            <h2 className="text-5xl md:text-6xl font-[1000] mb-6 text-slate-900 tracking-tight">Simple, transparent <span className="text-blue-600">pricing.</span></h2>
            <p className="text-xl text-slate-500 max-w-2xl mx-auto mb-20 font-medium">Choose the plan that's right for your growth.</p>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {/* Candidate Plan */}
            <div className="p-12 rounded-[50px] bg-slate-50 border border-slate-100 text-left hover:border-blue-200 transition-all">
              <h3 className="text-xl font-black mb-2 uppercase tracking-widest text-slate-400">For Talent</h3>
              <div className="flex items-baseline gap-1 mb-8">
                <span className="text-6xl font-[1000] text-slate-900">$0</span>
                <span className="text-slate-400 font-bold uppercase tracking-widest text-xs">Forever</span>
              </div>
              <div className="space-y-4 mb-12">
                {['AI Resume Scoring', 'Smart Roadmaps', 'Unlimited Applications', 'Mock Interviews'].map((item, idx) => (
                  <div key={idx} className="flex items-center gap-3 font-bold text-slate-600">
                    <Check size={18} className="text-blue-600" /> {item}
                  </div>
                ))}
              </div>
              <Link to="/register-candidate" className="block w-full py-5 bg-white border-2 border-slate-200 text-slate-950 text-center rounded-2xl font-black uppercase tracking-widest hover:border-blue-600 hover:text-blue-600 transition-all">Join Free</Link>
            </div>

            {/* Business Plan */}
            <div className="p-12 rounded-[50px] bg-slate-950 text-white text-left relative overflow-hidden shadow-2xl shadow-blue-500/20">
              <div className="absolute top-0 right-0 bg-blue-600 px-6 py-2 text-[10px] font-black uppercase tracking-[0.2em]">Popular</div>
              <h3 className="text-xl font-black mb-2 uppercase tracking-widest text-slate-500">For Recruiters</h3>
              <div className="flex items-baseline gap-1 mb-8">
                <span className="text-6xl font-[1000]">$99</span>
                <span className="text-slate-500 font-bold uppercase tracking-widest text-xs">/month</span>
              </div>
              <div className="space-y-4 mb-12">
                {['Neural Ranking', 'Deep Skill Analytics', 'Unlimited Job Posts', 'API Access'].map((item, idx) => (
                  <div key={idx} className="flex items-center gap-3 font-bold text-slate-300">
                    <Check size={18} className="text-blue-500" /> {item}
                  </div>
                ))}
              </div>
              <Link to="/register-candidate" className="block w-full py-5 bg-blue-600 text-white text-center rounded-2xl font-black uppercase tracking-widest hover:bg-blue-500 transition-all shadow-xl shadow-blue-600/30">Start Enterprise</Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- MARQUEE --- */}
      <div className="py-24 overflow-hidden border-y border-slate-100 bg-white mb-20">
        <motion.div animate={{ x: [0, -1800] }} transition={{ duration: 35, repeat: Infinity, ease: "linear" }} className="flex gap-20 whitespace-nowrap">
          {[1,2,3,4,5].map((i) => (
            <span key={i} className="text-9xl font-[1000] text-slate-100 uppercase tracking-tighter italic">
               SmartHire AI Ecosystem • Next Gen Talent • Ethical Intelligence • Seamless Matching • 
            </span>
          ))}
        </motion.div>
      </div>

      {/* --- FOOTER --- */}
      <footer id="contact" className="py-24 text-center border-t border-slate-100 bg-white px-6">
        <div className="flex items-center justify-center gap-2.5 mb-9">
          <BrainCircuit className="text-blue-600" size={32} />
          <span className="text-3xl font-[1000] tracking-tighter text-slate-950">SmartHire<span className="text-blue-500">.</span></span>
        </div>
        <p className="text-slate-400 font-bold text-xs uppercase tracking-[0.3em] mb-12">The Future of Intelligent Recruitment</p>
        <div className="flex justify-center gap-12 text-slate-500 font-black text-xs uppercase tracking-widest">
          <a href="#" className="hover:text-blue-600 transition-all">Privacy</a>
          <a href="#" className="hover:text-blue-600 transition-all">Terms</a>
          <a href="#" className="hover:text-blue-600 transition-all">Security</a>
          <a href="#" className="hover:text-blue-600 transition-all">Support</a>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;